# Importing Necessary Libraries

In [2]:
import pandas as pd
df = pd.read_csv('compiled.csv')

# Removing Empty Cells

In [3]:
df.dropna(inplace = True)
df

,Date,Time,Name,Message
3,09/12/2019,1:38 pm,Joshua Mbai,"Dear Team Wajir, please feel free to reach out..."
4,09/12/2019,1:39 pm,Joshua Mbai,Please share your account.
5,12/12/2019,7:09 pm,+254 725 351772,Forgot pasward kindly assist.sahara.wajir nort...
6,12/12/2019,7:22 pm,Lilian,You deleted this message
7,12/12/2019,7:33 pm,Lilian,"Your Username is :smohamed, Reset done use def..."
...,...,...,...,...
4936,05/12/2022,9:02 am,+254 722 251705,"Lilian Osero, please advise."
4937,05/12/2022,9:04 am,Violet Mastamet DCS,open in the browser childprotection.go.ke And ...
4938,03/01/2023,11:57 am,+254 722 251705,"Hi Lillian Osero, I have two pending cases in ..."
4940,09/02/2023,4:07 pm,Violet Mastamet DCS,"Good afternoon colleagues, first and foremost,..."
4941,09/02/2023,4:08 pm,Violet Mastamet DCS,<Media omitted> Bungoma.jpg\n

# Removing rows with Irrelevant Data

## e.g < Media Ommited>

In [4]:
df.drop(df[df['Message'] == '<Media omitted>'].index,inplace= True)
df.drop(df[df['Message'] == 'This message was deleted'].index,inplace= True)
df.dropna(inplace = True)
df

,Date,Time,Name,Message
3,09/12/2019,1:38 pm,Joshua Mbai,"Dear Team Wajir, please feel free to reach out..."
4,09/12/2019,1:39 pm,Joshua Mbai,Please share your account.
5,12/12/2019,7:09 pm,+254 725 351772,Forgot pasward kindly assist.sahara.wajir nort...
6,12/12/2019,7:22 pm,Lilian,You deleted this message
7,12/12/2019,7:33 pm,Lilian,"Your Username is :smohamed, Reset done use def..."
...,...,...,...,...
4936,05/12/2022,9:02 am,+254 722 251705,"Lilian Osero, please advise."
4937,05/12/2022,9:04 am,Violet Mastamet DCS,open in the browser childprotection.go.ke And ...
4938,03/01/2023,11:57 am,+254 722 251705,"Hi Lillian Osero, I have two pending cases in ..."
4940,09/02/2023,4:07 pm,Violet Mastamet DCS,"Good afternoon colleagues, first and foremost,..."
4941,09/02/2023,4:08 pm,Violet Mastamet DCS,<Media omitted> Bungoma.jpg\n

# Removing Duplicates

In [5]:
df.drop_duplicates(subset=None, keep='first', inplace=True, ignore_index=False)
df

,Date,Time,Name,Message
3,09/12/2019,1:38 pm,Joshua Mbai,"Dear Team Wajir, please feel free to reach out..."
4,09/12/2019,1:39 pm,Joshua Mbai,Please share your account.
5,12/12/2019,7:09 pm,+254 725 351772,Forgot pasward kindly assist.sahara.wajir nort...
6,12/12/2019,7:22 pm,Lilian,You deleted this message
7,12/12/2019,7:33 pm,Lilian,"Your Username is :smohamed, Reset done use def..."
...,...,...,...,...
4936,05/12/2022,9:02 am,+254 722 251705,"Lilian Osero, please advise."
4937,05/12/2022,9:04 am,Violet Mastamet DCS,open in the browser childprotection.go.ke And ...
4938,03/01/2023,11:57 am,+254 722 251705,"Hi Lillian Osero, I have two pending cases in ..."
4940,09/02/2023,4:07 pm,Violet Mastamet DCS,"Good afternoon colleagues, first and foremost,..."
4941,09/02/2023,4:08 pm,Violet Mastamet DCS,<Media omitted> Bungoma.jpg\n

In [8]:
df.drop(df[df['Message'] == 'This message was deleted'].index,inplace= True)
df

,Date,Time,Name,Message
3,09/12/2019,1:38 pm,Joshua Mbai,"Dear Team Wajir, please feel free to reach out..."
4,09/12/2019,1:39 pm,Joshua Mbai,Please share your account.
5,12/12/2019,7:09 pm,+254 725 351772,Forgot pasward kindly assist.sahara.wajir nort...
6,12/12/2019,7:22 pm,Lilian,You deleted this message
7,12/12/2019,7:33 pm,Lilian,"Your Username is :smohamed, Reset done use def..."
...,...,...,...,...
4936,05/12/2022,9:02 am,+254 722 251705,"Lilian Osero, please advise."
4937,05/12/2022,9:04 am,Violet Mastamet DCS,open in the browser childprotection.go.ke And ...
4938,03/01/2023,11:57 am,+254 722 251705,"Hi Lillian Osero, I have two pending cases in ..."
4940,09/02/2023,4:07 pm,Violet Mastamet DCS,"Good afternoon colleagues, first and foremost,..."
4941,09/02/2023,4:08 pm,Violet Mastamet DCS,<Media omitted> Bungoma.jpg\n

In [7]:
df

,Date,Time,Name,Message
3,09/12/2019,1:38 pm,Joshua Mbai,"Dear Team Wajir, please feel free to reach out..."
4,09/12/2019,1:39 pm,Joshua Mbai,Please share your account.
5,12/12/2019,7:09 pm,+254 725 351772,Forgot pasward kindly assist.sahara.wajir nort...
6,12/12/2019,7:22 pm,Lilian,You deleted this message
7,12/12/2019,7:33 pm,Lilian,"Your Username is :smohamed, Reset done use def..."
...,...,...,...,...
4936,05/12/2022,9:02 am,+254 722 251705,"Lilian Osero, please advise."
4937,05/12/2022,9:04 am,Violet Mastamet DCS,open in the browser childprotection.go.ke And ...
4938,03/01/2023,11:57 am,+254 722 251705,"Hi Lillian Osero, I have two pending cases in ..."
4940,09/02/2023,4:07 pm,Violet Mastamet DCS,"Good afternoon colleagues, first and foremost,..."
4941,09/02/2023,4:08 pm,Violet Mastamet DCS,<Media omitted> Bungoma.jpg\n